### PR TITLE
App Icon & UI Improvements

### PR DESCRIPTION
**Pull request by thegamingninja**
Changes
---
* Added App Icon
* Added Show TTS option to enable TTS mode
* Added Show Intent option to show intent data
* Cleaned Up Home Screen
* Improved Settings Screen

Reason for Changes
---
This is a very cool and useful project, and I really appreciate all the work put into it, so I wanted to contribute by making it look and feel more polished.

Screenshots
---
image
image

### CODE REVIEW

**Comment by razzo04** [comment]
Thank you a lot for your participation in this project and for the redesign of the home screen and settings screen, I’m not very good at making UI. I will review and test the code as soon as possible.

**Comment by thegamingninja** [comment]
> Thank you a lot for your participation in this project and for the redesign of the home screen and settings screen, I’m not very good at making UI. I will review and test the code as soon as possible.

No problem. I was testing it today and noticed a few bugs, so I'll fix those and make another commit when I'm available.

**Comment by thegamingninja** [comment]
I fixed the issues I was experiencing from the changes I made, so everything should be good to go now.

**Review by razzo04 — APPROVED** [review]
I tested the application and it seems to work. I found small bugs but since I noticed that several people have shown interest in the project I want to continue making improvements that will change most of the code so before publishing a new version with the changes you made will be some time. Thank you very much for your contribution!

**Pull request merged**
